version: '3'
services:
  localstack:
    image: localstack/localstack:0.11.2
    environment:
      - SERVICES=dynamodb
    ports:
      - 4566:4566
      - 4571:4571
      - 4510-4530:4510-4530
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"